### PR TITLE
Aarong chapter21

### PR DESCRIPTION
**Pull request by spitakiss**

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
My apologies! This came in just before a vacation, and got buried in my inbox. I think there's an issue with the build; I'll try to fix it if so, but let me know if you're able to fix it! Either way, I'm marking this approved for now in case the build succeeds. Thanks!

**Review by jonthegeek — APPROVED** [review]
Re-approving in case it passes now.

**Comment by jonthegeek** [comment]
@spitakiss Whenever you use a package in a book club (or when writing an R package or bookdown book), run `usethis::use_package(pkgname)`, eg `usethis::use_package("GGally")`. In rare cases (eg tidymodels) you might need to follow the instructions usethis gives in response.

That way the slider-builder knows which packages it needs in order to render the slides.

I think I've fixed all the issues now. Thanks again!

**Comment by spitakiss** [comment]
@jonthegeek -- Pardon my delayed response. Thanks for the comments and fixes. I will try to address these potential issues moving forward.

**Pull request merged**
